version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
    open-pull-requests-limit: 10
    reviewers:
      - MaximeMichaud
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci(deps)"
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
    open-pull-requests-limit: 10
    reviewers:
      - MaximeMichaud
    labels:
      - dependencies
      - .NET
    cooldown:
      default-days: 3
      semver-major-days: 14
    commit-message:
      prefix: "build(deps)"
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: "npm"
    directory: "/src/Web/vue-app"
    schedule:
      interval: "weekly"
      day: monday
    open-pull-requests-limit: 10
    reviewers:
      - MaximeMichaud
    labels:
      - dependencies
      - frontend
    versioning-strategy: increase-if-necessary
    cooldown:
      default-days: 3
      semver-major-days: 14
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
    groups:
      npm-prod-minor-patch:
        dependency-type: "production"
        update-types:
          - minor
          - patch
      npm-dev-minor-patch:
        dependency-type: "development"
        update-types:
          - minor
          - patch
